10th task
KebabJoy/Test-Guru pull request #11
Opened 2021-02-27 13:49 UTC by KebabJoy

1. Реализуйте аутентификацию в проекте при помощи библиотеки Devise
2. Сделайте управление ресурсами вопросов и ответов доступным только для администраторов
3. С помощью хэлпера Devise реализуйте перенаправление администраторов на страницу /admin/tests после логина
4. При создании нового теста администратором назначайте его в качестве автора теста

Усложненное задание:

При регистрации пользователя запрашивать его имя и фамилию и после входа, выводить флэш-сообщение "Привет, <имя пользователя>!"

2021-03-01 07:25 UTC, VidgarVii requested changes

2021-03-01 07:25 UTC, VidgarVii commented on app/controllers/application_controller.rb
>    end
данный метод отвечает только за редирект юзера после логина. Добавлять нотификацию было бы слишком наивно) Это нарушает принцеп [SRP](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8) 

Вывод флеш надо ставить там где происходит создание сессии. Вспоминай прошлый урок

2021-03-01 07:25 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    user.type == 'Admin' ? admin_tests_path : root_path
не совсем корректный полиморфизм. Надо использовать метод дополнения, а не замещения. Иначе ломаешь функционал devise
Посмотри рекомендации по данному методу
[рекомендация](https://www.rubydoc.info/github/plataformatec/devise/Devise/Controllers/Helpers:after_sign_in_path_for)

2021-03-01 07:25 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :set_test, only: %i[start]
лишний колбек

2021-03-01 07:32 UTC, KebabJoy commented on app/controllers/tests_controller.rb
> +  before_action :set_test, only: %i[start]
Почему лишний? Нам же надо добавить тест текущему пользователю. В самом старте не логично, думаю, искать тест

2021-03-01 13:24 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    user.type == 'Admin' ? admin_tests_path : root_path
не исправил

2021-03-01 13:25 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :set_test, only: %i[start]
код должен быть явный. Как раз в методе старта теста и надо найти этот тест. 
Для 1 метода колбек не пишем

2021-03-01 13:26 UTC, VidgarVii requested changes

2021-03-01 13:26 UTC, VidgarVii commented on app/controllers/registrations_controller.rb
> +    flash[:notice] = "Hello! #{current_user.first_name} #{current_user.last_name}!"
flash надо написать в самом методе create

2021-03-01 13:33 UTC, KebabJoy commented on app/controllers/registrations_controller.rb
> +    flash[:notice] = "Hello! #{current_user.first_name} #{current_user.last_name}!"
Сначала так и сделал, но подумал, что нужно декомпозицию сделать, ведь та же проблема, что и с методом after_sign_in_path_for - метод создает сессию, зачем выводить в нём сообщение :(

2021-03-01 18:21 UTC, VidgarVii commented on app/controllers/registrations_controller.rb
> +    flash[:notice] = "Hello! #{current_user.first_name} #{current_user.last_name}!"
rails way

2021-03-02 05:39 UTC, VidgarVii commented on app/controllers/registrations_controller.rb
> +    super
это под удаление. После регистарации по дефолту юзера отправляют подтверждать почту

2021-03-02 09:38 UTC, merged