5th_task final
KebabJoy/Test-Guru pull request #5
Opened 2020-12-26 18:25 UTC by KebabJoy

1. Определите scope-методы:
* для выбора правильных Ответов
* Для выбора Тестов по уровню сложности:
* простой (нулевой или первый уровень),
       средний (со второго по четвёртый),
       сложный (с пятого и выше). * Значение положительной бесконечности можно получить с помощью константы Float::INFINITY
scope-метод по умолчанию для получения Категорий, отсортированных по названию в порядке возрастания

2. Используйте scope-методы вместо методов моделей, которые были определены в предыдущих заданиях

3. Определите валидации данных:
Наличие атрибутов title, body, email в соответствующих моделях
* Уровень Теста может быть только положительным целым числом
* Может существовать только один * Тест с данным названием и уровнем
* У одного Вопроса может быть от 1-го до 4-х ответов.

2020-12-26 19:16 UTC, VidgarVii requested changes

2020-12-26 19:16 UTC, VidgarVii commented on app/models/question.rb
> +    def answers_limit
ТЗ: "У одного Вопроса может быть от 1-го до 4-х ответов."
не очень понятно как валидация в модели Вопрос будет препятствовать созданию новых ответов в количестве больше 4... она же не будет вызываться, когда ты будешь добавлять новые ответы к вопросу - вызываются валидации того класса, объекты которого создаются

при создании нового объекта класса Ответ вызываются валидации класса Ответ, а не класса Вопрос

видимо ты не проверяла работу этой валидации

2020-12-26 19:16 UTC, VidgarVii commented on app/models/test.rb
> +  scope :easy, -> { where(level: 0..1).order(created_at: :desc) }
как называние скоупа связан с сортировкой данных?
по ДЗ не было задач сортировать тесты

2020-12-26 19:16 UTC, VidgarVii commented on app/models/test.rb
> +  scope :with_category, -> (category) { Test.joins(:category)
внутри скоупа `self` равен самому классу (по сути скопы - метода класса), поэтому явно указывать класс внутри скоупа не нужно (и его никогда не указывают)

2020-12-26 19:16 UTC, VidgarVii commented on app/models/test.rb
> +                                        .where(["categories.title = ?", category])}
безопасней использовать синтаксис ruby
where({categories: {title: category} })
category - не говорящее название аргумента

2020-12-26 19:16 UTC, VidgarVii commented on app/models/test.rb
> +
разбивай группы методов на логические блоки с помощью переноса строки.
https://github.com/rubocop-hq/rails-style-guide#macro-style-methods

2020-12-26 19:16 UTC, VidgarVii commented on app/models/user.rb
> +        with_level, user_tests: { user_id: id })
тут явно не проверенный код на лицо

2020-12-26 22:55 UTC, KebabJoy commented on app/models/question.rb
> +    def answers_limit
По идее же стоит "on: :update" и при обновлении вопроса будет валидация вызывать метод. А на ответ ставить валидацию не совсем очевидно, ведь делать, обращаясь к вопросу надо получается
Поправьте, если не так понимаю
Но переделаю тогда сейчас всё равно

2020-12-26 22:56 UTC, KebabJoy commented on app/models/test.rb
> +  scope :easy, -> { where(level: 0..1).order(created_at: :desc) }
В тупую списал из лекции =/

2020-12-26 22:57 UTC, KebabJoy commented on app/models/test.rb
> +                                        .where(["categories.title = ?", category])}
В документации был написан такой метод для защиты от sql injection'ов

2020-12-27 12:18 UTC, VidgarVii commented on app/models/answer.rb
> +    validate :answers_limit, on: :create
валидации должны идти после объявление связей. (не относится к default_scope )

2020-12-27 12:18 UTC, VidgarVii commented on app/models/category.rb
> +    default_scope {order(title: :asc)}
default_scope должен быть первым. далее объявляются связи

2020-12-27 12:35 UTC, merged