6th task
KebabJoy/Test-Guru pull request #6
Opened 2020-12-28 00:54 UTC by KebabJoy

1. Создайте ресурс Вопросов, вложенный в ресурс Тестов

2. Следуя принципам  REST, cоздайте контроллер для ресурса вопросов и реализуйте методы:
* Просмотра списка вопросов теста
* Просмотра конкретного вопроса теста
* Создания вопроса. Используйте шаблон с HTML формой. Идентификатор теста к которому принадлежит вопрос можно указать явно в составе URL значения атрибута action в тэге form
* Удаления вопроса
* Используйте метод render внутри действия контроллера чтобы вернуть ответ клиенту как простой текст (plain text) или HTML
* Используйте обратный вызов при поиске теста в контроллере ресурса вопросов

3. Напишите обработку исключения для случая когда вопрос не был найден

2020-12-28 04:15 UTC, VidgarVii requested changes

2020-12-28 04:15 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    def list
для спсика вопросов у тебя есть index

2020-12-28 04:15 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +       redirect_to :action => 'list'
в redirect_to лучше использовать хелперы маршрутов. rails way

2020-12-28 04:15 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +
1 все методы ниже у тебя в данный момент являются экшенами. Так не должно быть. Надо исправить
2 нет экшена для Просмотра конкретного вопроса теста

2020-12-28 04:18 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/questions/<%= params[:question_id] %>" method="post">
для удаления используют метод delete
и можно сделать ввиде ссылки на экшен

2020-12-28 07:32 UTC, KebabJoy commented on app/views/questions/new.html.erb
> +<form action="/questions/<%= params[:question_id] %>" method="post">
Разве у формы в методе не принято писать get || post?
На htmlbook так написано

2020-12-28 12:45 UTC, VidgarVii requested changes

2020-12-28 12:45 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    before_action :find_test
куда пропали красивые отступы в 2 пробела?

2020-12-28 12:45 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +
тут не нужна пустая строка

2020-12-28 12:45 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +       render plain: @question.body
от куда у тебя @question берется??

2020-12-28 12:45 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +       # byebug
отладочный код надо убирать. вижу что ПР не проверялся

2020-12-28 12:45 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    def show
первым экшеном в списке как правило идет index. далее show
Сделай scaffold и глянь шаблоны

2020-12-28 12:45 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +        @question = Test.new(question_params)
???????

2020-12-28 17:38 UTC, VidgarVii requested changes

2020-12-28 17:38 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :set_question
не для каждого экшена нужны данные с этих колбеков. надо прописывать название экшенов для которых были созданы эти колбеки.

2020-12-28 17:38 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Question.new(question_params)
для какого теста будет создан вопрос?

2020-12-28 17:38 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    Question.find(params[:test_id]).destroy
у тебя ведь колбек уже ищет нужный вопрос

2020-12-28 17:38 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render plain: "#{params[:title]} not found"
Проверь что будет содержать params[:title]

2020-12-30 07:40 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  end
пока до партиалов не дошли. Но это не значит, что можно оставлять не рабочий код.
все страницы должны открываться и показывать пользователю ожидаемые то данные

2020-12-30 07:40 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/questions/<%= params[:question_id] %>" method="post">
прочитай про http и rest о том какие еще методы бывают и для чего они используются. По моему в видео уроках об этом уже говорилось

2021-02-05 06:55 UTC, VidgarVii requested changes

2021-02-05 06:55 UTC, VidgarVii commented on db/migrate/20201223065454_create_users.rb
> +      t.integer :user_id
для чего это поле? миграции уже создают поле для id

2021-02-05 06:55 UTC, VidgarVii commented on db/seeds.rb
> +                      { title: "MIPT olympiad", level: 4, category_id: categories[1].id, author_id: users[0].id }
декларативность наше всё
{ title: "MIPT olympiad", level: 4, category: categories[1], author:  user[0] }

2021-02-05 06:55 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +
судя по ссылки это форма для создания вопроса, а не удаления. Чтобы что-то удалить форма не нужна. Достаточно одной ссылки

2021-02-05 06:55 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: "user_id"
нет такого поля user_id у теста

2021-02-05 06:55 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Question.new(question_params)
не исправил

2021-02-05 06:55 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to :index
для redirect_to используй url helper или объект
redirect_to @question

2021-02-05 17:31 UTC, VidgarVii requested changes

2021-02-05 17:31 UTC, VidgarVii commented on db/seeds.rb
> +                             ])
переменные user_tests и answers не используются. Надо удалить

2021-02-05 17:31 UTC, VidgarVii commented on db/seeds.rb
> +                              { user_id: users[1].id, test_id: tests[0].id }
надо передавать объекты юзера и теста

2021-02-05 17:31 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  end
так и не заработала страница =(

2021-02-05 17:31 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
тут явно чего-то не хватает....

2021-02-05 17:31 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
сюда не приходят ни какие параметры. Надо вернуть читсый объект

2021-02-05 17:31 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
проверь всё руками

2021-02-08 04:50 UTC, VidgarVii requested changes

2021-02-08 04:50 UTC, VidgarVii commented on config/routes.rb
> +  get '/tests/:test_id/questions/:question_id', to: 'questions#show'
проверь какие маршруты у тебя уже есть. И не надо их дублировать.

2021-02-09 19:23 UTC, merged