8th_task done
KebabJoy/Test-Guru pull request #8
Opened 2021-02-21 21:40 UTC by KebabJoy

1. Сделайте назначение следующего вопроса в модели TestPassage с помощью обратного вызова
2. Доработайте шаблон результата прохождения теста:
- Выводите сообщение и процент успеха в зависимости от количества правильных ответов
- Если процент успеха >= 85% число должно быть зелёного цвета и сообщение должно говорить об успешном прохождении теста
- Если процент успеха < 85% число должно быть красного цвета и сообщение должно говорить о том что тест не пройден
- Добавьте навигацию в виде ссылки на список всех тестов
3. Доработайте шаблон отображения прохождения теста:
- Выводите номер текущего вопроса и общее количество вопросов теста

Возможен более простой способ реализации проверки правильного ответа:

correct_answers.ids.sort == answer_ids.map(&:to_i).sort

2021-02-22 17:36 UTC, VidgarVii requested changes

2021-02-22 17:36 UTC, VidgarVii commented on app/models/test_passage.rb
> +    stats > 85.0
лучше "магические цифры" хранить в константах с "говорящими именами"
 `stats > 85.0` не совсем корректно выполняет требования ТЗ

2021-02-22 17:36 UTC, VidgarVii commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
если юзер не выберет ответ будет баг.

2021-02-22 17:36 UTC, VidgarVii commented on app/models/user.rb
> +    has_many :tests, through: :test_passages
тут баг на лицо

2021-02-22 17:36 UTC, VidgarVii commented on app/models/user.rb
>          tests.where(level: lvl) # По идее за счет ассоциации пользователь имеет только свои тесты
комментарий сбивает с толку

2021-02-23 16:27 UTC, VidgarVii commented on db/seeds.rb
> +test_passages = TestPassage.create!([
переменные которые не используются мешают сборщику мусора

2021-02-23 16:27 UTC, VidgarVii commented on app/models/test_passage.rb
> +  SUCCESS_RATE = 85.0.freeze
числа не фризят. Они уже заморожены

2021-02-23 16:27 UTC, VidgarVii commented on app/models/test_passage.rb
> +    test_result > SUCCESS_RATE
условие не соответствует ДЗ

2021-02-23 16:27 UTC, VidgarVii commented on app/models/test_passage.rb
> +    end
guard clause!
```
return unless answer_ids
```

2021-02-23 16:27 UTC, VidgarVii commented on app/models/user.rb
> +    has_many :tests, through: :test_passages
не исправил

2021-02-23 16:33 UTC, KebabJoy commented on app/models/user.rb
> +    has_many :tests, through: :test_passages
а в чём проблема то тут?

2021-02-24 17:56 UTC, merged